package com.myra.assistant.commands

enum class CommandType {
    OPEN_APP, CLOSE_APP, SEARCH_YOUTUBE, REPEAT_YOUTUBE_SEARCH, DEEP_RESEARCH,
    REPLY_WHATSAPP, QUERY_WHATSAPP, GO_HOME, GO_BACK, CURRENT_TIME,
    BATTERY_LEVEL, FLASHLIGHT_ON, FLASHLIGHT_OFF, UNKNOWN
}
