package com.myra.assistant.commands

enum class CommandType {
    OPEN_APP, CLOSE_APP, SEARCH_YOUTUBE, PLAY_YOUTUBE, OPEN_YOUTUBE_SHORTS,
    REQUEST_INSTAGRAM_REELS, OPEN_INSTAGRAM_REELS, TAKE_SCREENSHOT,
    REPEAT_YOUTUBE_SEARCH, DEEP_RESEARCH,
    REPLY_WHATSAPP, QUERY_WHATSAPP, GO_HOME, GO_BACK, CURRENT_TIME,
    BATTERY_LEVEL, LIST_FEATURES, FLASHLIGHT_ON, FLASHLIGHT_OFF,
    MEDIA_PAUSE, MEDIA_PLAY, MEDIA_NEXT, MEDIA_PREVIOUS, MEDIA_FIRST,
    YOUTUBE_SCROLL_DOWN, YOUTUBE_SCROLL_UP, YOUTUBE_SCROLL_REPEAT, UNKNOWN
}
